// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fogcptazoudinbgfgiyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvZ2NwdGF6b3VkaW5iZ2ZnaXl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NTM3MDMsImV4cCI6MjA2NzUyOTcwM30.OPV_Sdlnbku1A0ptcZzvJLiiReEsK7OfX14Mve1TKHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});